# Generated by Django 5.1 on 2024-08-18 01:15

from django.db import migrations


def create_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    admin_group, created = Group.objects.get_or_create(name="Administrador")

    # Añadir permisos específicos al rol admin
    Permission = apps.get_model('auth', 'Permission')
    some_permission = Permission.objects.get(codename='some_permission')
    admin_group.permissions.add(some_permission)


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth",
            "0012_alter_user_first_name_max_length",
        ),  # Asegúrate de que el archivo de migración sea correcto
    ]

    operations = [
        migrations.RunPython(create_admin_group),
    ]
