# Generated by Django 5.1 on 2024-08-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0003_alter_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="direccion",
        ),
    ]
