# Generated by Django 5.1 on 2024-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_remove_userprofile_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=80, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número de teléfono'),
        ),
    ]
