# Generated by Django 5.1 on 2024-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0006_userprofile_pagos"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_notifications",
            field=models.BooleanField(
                default=False,
                verbose_name="Desee recibir notificaciones sobre nuevas publicaciones?",
            ),
        ),
    ]
