# Generated by Django 5.1 on 2024-10-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0008_alter_userprofile_receive_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="c_aprobados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="c_audit_eliminados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="c_audit_publicados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="c_audit_rechazados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="c_audit_revisados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="c_creados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="c_publicados",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="c_rechazados",
            field=models.IntegerField(default=0),
        ),
    ]
