# Generated by Django 5.1 on 2024-10-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reports", "0002_rename_created_at_report_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="is_handled",
            field=models.BooleanField(default=False),
        ),
    ]
