# Generated by Django 5.1 on 2025-02-03 17:34

import django.utils.timezone
import modulos.mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destacado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de destacado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creacion",
                    ),
                ),
                (
                    "message",
                    models.CharField(max_length=800, verbose_name="description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Titulo")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posts_images/",
                        verbose_name="Portada",
                    ),
                ),
                (
                    "content",
                    modulos.mdeditor.fields.MDTextField(verbose_name="Contenido"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Borrador", "Borrador"),
                            ("Esperando revision", "Esperando revision"),
                            ("Esperando publicacion", "Esperando publicacion"),
                            ("Publicado", "Publicado"),
                        ],
                        default="Borrador",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creacion",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de publicacion"
                    ),
                ),
                (
                    "scheduled_publication_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de publicacion agendada",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de validez"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=80, verbose_name="tags"),
                ),
                ("version", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField()),
                ("title", models.CharField(max_length=80, verbose_name="Titulo")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posts_images/",
                        verbose_name="Portada",
                    ),
                ),
                (
                    "content",
                    modulos.mdeditor.fields.MDTextField(
                        null=True, verbose_name="Contenido"
                    ),
                ),
                ("status", models.CharField(max_length=30, verbose_name="Status")),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de creacion",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de publicacion"
                    ),
                ),
                (
                    "scheduled_publication_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de publicacion agendada",
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=80, verbose_name="tags"),
                ),
                ("version", models.IntegerField(default=0)),
            ],
        ),
    ]
