# Generated by Django 5.1 on 2024-09-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Categories", "0004_category_status_category_tipo"),
        ("Posts", "0002_remove_post_category_remove_post_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="Categories.category",
            ),
        ),
    ]
