# Generated by Django 5.1 on 2024-09-06 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0005_remove_post_tags_post_author_post_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
