# Generated by Django 5.1 on 2024-09-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0008_alter_post_author_alter_post_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorite",
            field=models.BooleanField(default=False, verbose_name="Favorito"),
        ),
    ]
