# Generated by Django 5.1 on 2024-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0008_alter_post_author_alter_post_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Borrador", "Borrador"),
                    ("Esperando revision", "Esperando revision"),
                    ("Esperando publicacion", "Esperando publicacion"),
                    ("Publicado", "Publicado"),
                    ("Rechazado", "Rechazado"),
                    ("INACTIVE", "INACTIVE"),
                ],
                default="Borrador",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
