# Generated by Django 5.1 on 2024-09-21 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0009_post_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="favorite",
        ),
        migrations.AddField(
            model_name="post",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favoritos",
            ),
        ),
    ]
