# Generated by Django 5.1 on 2024-09-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0010_post_publication_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Posts.post",
                    ),
                ),
                ("post_id", models.IntegerField()),
            ],
            bases=("Posts.post",),
        ),
        migrations.AddField(
            model_name="post",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
