# Generated by Django 5.1 on 2024-09-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0010_alter_post_category"),
        ("Posts", "0011_post_publication_date_and_more"),
    ]

    operations = []
