# Generated by Django 5.1 on 2024-09-30 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0012_merge_20240930_0143"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Favoritos",
            ),
        ),
    ]
