# Generated by Django 5.1 on 2024-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0014_post_version_log_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
