# Generated by Django 5.1 on 2024-10-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0015_alter_post_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Borrador", "Borrador"),
                    ("Esperando revision", "Esperando revision"),
                    ("Esperando publicacion", "Esperando publicacion"),
                    ("Publicado", "Publicado"),
                ],
                default="Borrador",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
