# Generated by Django 5.1 on 2024-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0016_post_active_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de validez"
            ),
        ),
    ]
