# Generated by Django 5.1 on 2024-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0003_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="Posts.tag"),
        ),
    ]
