# Generated by Django 5.1 on 2024-09-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Posts", "0006_alter_post_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts_images/"),
        ),
    ]
