# Generated by Django 5.1 on 2024-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=80, verbose_name="Nombre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrición"),
                ),
            ],
        ),
    ]
