# Generated by Django 5.1 on 2024-09-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Categories", "0002_alter_category_description_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrición"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=80, verbose_name="Nombre"),
        ),
    ]
