# Generated by Django 5.1 on 2024-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Categories", "0003_alter_category_description_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                default="ACTIVO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="tipo",
            field=models.CharField(
                choices=[("PREMIUM", "Premium"), ("GRATIS", "Gratis")],
                default="GRATIS",
                max_length=10,
            ),
        ),
    ]
