# Generated by Django 5.1 on 2024-09-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Categories", "0005_alter_category_description_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Imagen de la categoría",
            ),
        ),
    ]
