# Generated by Django 5.1 on 2024-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tipo',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Gratis', 'Gratis'), ('Suscripcion', 'Suscripcion')], default='Gratis', max_length=15),
        ),
    ]
