# Generated by Django 5.1 on 2024-09-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="created_at",
            new_name="creation_date",
        ),
    ]
